---
# Playbook para cambiar configuracion de firewall en Ubuntu

- name: Change ufw 
  hosts: ubuntu
  become: true

  tasks:

  - name: Install UFW # Instala ufw en caso de que no este presente en el servidor
    ansible.builtin.apt:
      name: ufw
      state: present

  - name: Deny every incoming connection 
    community.general.ufw:
      direction: incoming
      policy: deny

  - name: Allow SSH connections
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Enable UFW
    community.general.ufw:
      state: enabled

  - name: Check authorized_key exist
    ansible.posix.authorized_key:
      user: sysadmin
      state: present
      key: "{{ lookup('file', '/home/sysadmin/.ssh/id_rsa.pub') }}" 


  - name: Login only with public/private key
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#PasswordAuthentication'
      line: PasswordAuthentication no
    notify: Restart SSH service


  handlers:

  - name: Restart SSH service
    ansible.builtin.service:
      name: ssh
      state: restarted     

    
