---
# Playbook para confguracion de virtual host para www.ejemplo.com.uy

- name: Virtual Host Config
  hosts: webserver
  become: true    # agrega sudo a la ejecucion de la tarea remota

  tasks:
  
  - name: Add information to host file
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "192.168.56.20 www.ejemplo.com.uy"
      state: present
    delegate_to: localhost
    connection: local

      #  - name: Modify Apache
      #ansible.builtin.lineinfile:
      #path: /etc/httpd/conf/httpd.conf
      #line: "IncludeOptional /etc/httpd/vhost.d/conf"
      #notify: Reiniciar Apache

  - name: Create Directory for Virtual Host
    ansible.builtin.file:
      path: "/var/www/ejemplo/html" # crea el directorio
      state: directory
      owner: apache
      group: apache
      mode: '0755'

  - name: Virtual Host
    ansible.builtin.template:
      src: ./templates/virtualhost.j2
      dest: "/etc/httpd/conf.d/ejemplo.conf" # copia la configuracion realizada en el archivo virtualhost.j2 en la ubicacion especifica del webserver
      owner: root
      group: root
      mode: '0644'
    notify: Reiniciar Apache

  - name: Index.html
    ansible.builtin.template:
      src: ./templates/index.j2
      dest: "/var/www/ejemplo/html/index.html" # copia la pagina index realizada previamente
      owner: apache
      group: apache
      mode: '0644'

  handlers:

  - name: Reiniciar Apache
    ansible.builtin.service:
      name: httpd
      state: restarted
